### ISSUE TITLE
same fields on different levels

### ISSUE THREAD

**Issue by telephon** [yaxu/Clean-dirty#2]
I find it not idal that the same field name is used on different levels of the json file (`"shortname"`). Better to call them differently, I think.

**Comment by yaxu** [comment]
Yes I've been wondering about this. `soundset_id` and `sound_id`?

**Comment by yaxu** [comment]
I think the only thing that I find problematic about this is that for some things e.g. license you might set a default at the top level that you override on lower levels. The case of 'shortname' doesn't quite fit that.

But then we're used to different types of things in a tree having an 'id', for example in css. So maybe we just call them `id` on both levels and make it required.

**Comment by yaxu** [comment]
Lets move discussion to https://github.com/tidalcycles/Clean-Samples/issues/14

**Comment by telephon** [comment]
Is the whole thing a "soundset" or a "sample bank"? The latter might be more common?

**Comment by yaxu** [comment]
I'm thinking there could be .scd or .pd as well as .wav files. So 'sample bank' isn't broad enough. 'sound bank' might be ok? Then again it could be nice to share videos or fonts in this way too. But 'media bank' might sound a bit silly? 'file bank'? Now it's feeling a bit too general.. 'OSC' isn't really about sound but was made for people interested in sound.

**Comment by yaxu** [comment]
Or maybe we just call it a 'bank'

**Comment by telephon** [comment]
yes, perhaps. 

"the tides break on the bank"

Where it is used, it ends up as a combination of two parameters `s` (a name) and `n` (a number). 
So it assumes an ordered collection of related things.
https://www.wordhippo.com/what-is/another-word-for/bunch.html

**Comment by yaxu** [comment]
I'm thinking we could refer to the sample by name as well as by number, i.e. support looking up sample by its id in the metadata. Then it would be nice if these could be equivalent:
```
d1 $ n "0 [~ 1]" # bank "drum"
d1 $ n "kick [~ snare]" # bank "drum"
```
That would be hard to implement though.

**Comment by telephon** [comment]
Assuming that "kick" is a name of a sample in the bank, right? This would not be that hard to implement.

**Comment by telephon** [comment]
The main problem is that it may be a little bit obscure.

**Comment by yaxu** [comment]
Well I think it would be nice to have a more general way of working with metadata in Tidal. For example for numeric data like spectral centroid, moving through a bank as a sorted list from `0 .. 1` with `d1 $ segment 16 $ metaF "centroid" sine # sound "river"`. So then we could have `name = metaS "sound_id"` (or whatever we call it) and then do `d1 $ name "kick" # sound "drum"`. 

Probably it would make sense for most of this to happen in Tidal then.
